# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GiboGo < Formula
  desc ""
  homepage "https://github.com/simonwhitaker/gibo-go"
  version "3.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.1/gibo-go_Darwin_x86_64.tar.gz"
      sha256 "1cf13dc3055e1be82d2ea6110113a5c08535b729e8d9f2d7ecf75e2a34050586"

      def install
        bin.install "gibo-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.1/gibo-go_Darwin_arm64.tar.gz"
      sha256 "d251a991bcb8d2eb6a696d1fbfc7a52f5ceeccf506dbee6e4da9a7f001e41a8d"

      def install
        bin.install "gibo-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.1/gibo-go_Linux_arm64.tar.gz"
      sha256 "478801a6cf467b522f685dbcff1d3f09eee6b58e181514009ae94df7e788a1c4"

      def install
        bin.install "gibo-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.1/gibo-go_Linux_x86_64.tar.gz"
      sha256 "766ae215bd2f7f8af37e2cdf6710292b629152bdc4a770dddbb730a125a01852"

      def install
        bin.install "gibo-go"
      end
    end
  end
end
