# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GiboGo < Formula
  desc ""
  homepage "https://github.com/simonwhitaker/gibo-go"
  version "3.0.0-beta.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.0-beta.4/gibo-go_Darwin_arm64.tar.gz"
      sha256 "36363a55c1fce3f9d81376cd8f9626d16ccbb7966f01cfe98ac04e0af977a435"

      def install
        bin.install "gibo-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.0-beta.4/gibo-go_Darwin_x86_64.tar.gz"
      sha256 "42439d80d7cbf0e799117210e958e7f4948ddf89b5f1489ca9f93bb73e27a084"

      def install
        bin.install "gibo-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.0-beta.4/gibo-go_Linux_x86_64.tar.gz"
      sha256 "4bbfea19072082f21c335b4abf298e3db7f019da6e188887e91f0c2273051661"

      def install
        bin.install "gibo-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.0-beta.4/gibo-go_Linux_arm64.tar.gz"
      sha256 "16eba4f6aa09af62e2037d7cdad7d125e783b636f581adec80c448a80a9ccfd0"

      def install
        bin.install "gibo-go"
      end
    end
  end
end
