# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GiboGo < Formula
  desc ""
  homepage "https://github.com/simonwhitaker/gibo-go"
  version "3.0.0-beta.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.0-beta.5/gibo-go_Darwin_arm64.tar.gz"
      sha256 "e8c7ad5be7e781a72a422512b957c9d0a517d27e4e5160a8c16a8c8602ef7b9a"

      def install
        bin.install "gibo-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.0-beta.5/gibo-go_Darwin_x86_64.tar.gz"
      sha256 "9e120be1d46c3d4473f15162e71fed7511c5c0676d07a8f4f2823e1e6a65cc43"

      def install
        bin.install "gibo-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.0-beta.5/gibo-go_Linux_arm64.tar.gz"
      sha256 "c03da8eacd07f17974a5c441c19dae6884c9ed1287316506a9e7f3773c461527"

      def install
        bin.install "gibo-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonwhitaker/gibo-go/releases/download/v3.0.0-beta.5/gibo-go_Linux_x86_64.tar.gz"
      sha256 "442f4ac87d939bb2a6dd5f6636dc898360c82ed0caf26d91dd1effa2cf291f4e"

      def install
        bin.install "gibo-go"
      end
    end
  end
end
