# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gibo < Formula
  desc ""
  homepage "https://github.com/simonwhitaker/gibo"
  version "3.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/simonwhitaker/gibo/releases/download/v3.0.8/gibo_Darwin_arm64.tar.gz"
      sha256 "dcc045107755d49e25bd3c22c72e155db7c38b18914af0177ad4993434259e3a"

      def install
        bin.install "gibo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonwhitaker/gibo/releases/download/v3.0.8/gibo_Darwin_x86_64.tar.gz"
      sha256 "9f4b96cd5a55f817e4a8c7ec8da177a576f0adf13049f23aa1624921d3438cbf"

      def install
        bin.install "gibo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonwhitaker/gibo/releases/download/v3.0.8/gibo_Linux_arm64.tar.gz"
      sha256 "4726657aecf99959b8c89c59719ba54485fcfa262a4c3e5b28d7a24b9a72ad06"

      def install
        bin.install "gibo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonwhitaker/gibo/releases/download/v3.0.8/gibo_Linux_x86_64.tar.gz"
      sha256 "b80687fb16086e1d21baf923bed730ea469f3332085a4aa8832aa13fe7e4cccd"

      def install
        bin.install "gibo"
      end
    end
  end
end
