# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runny < Formula
  desc ""
  homepage "https://github.com/simonwhitaker/runny"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/runny/releases/download/v0.0.1/runny_Darwin_x86_64.tar.gz"
      sha256 "788f15374ec700f4285c30beb7ea52ac85c0afe7a94108bfe083987f2c4da316"

      def install
        bin.install "runny"
        bash_completion.install "completions/runny.bash" => "runny"
        fish_completion.install "completions/runny.fish"
        zsh_completion.install "completions/runny.zsh" => "_runny"
      end
    end
    on_arm do
      url "https://github.com/simonwhitaker/runny/releases/download/v0.0.1/runny_Darwin_arm64.tar.gz"
      sha256 "f00e36c741646bd6a7703b36e7dc0a8d7de9329a0058f994193638bd7ae70235"

      def install
        bin.install "runny"
        bash_completion.install "completions/runny.bash" => "runny"
        fish_completion.install "completions/runny.fish"
        zsh_completion.install "completions/runny.zsh" => "_runny"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonwhitaker/runny/releases/download/v0.0.1/runny_Linux_x86_64.tar.gz"
        sha256 "1fe75ff933e3cf61933cd8eae200e37f1461b791db442d0de868c00cb1673aa1"

        def install
          bin.install "runny"
          bash_completion.install "completions/runny.bash" => "runny"
          fish_completion.install "completions/runny.fish"
          zsh_completion.install "completions/runny.zsh" => "_runny"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonwhitaker/runny/releases/download/v0.0.1/runny_Linux_arm64.tar.gz"
        sha256 "17f3f5f0f89365ac4aac7bc9d6d40fb98bb22ba5f350f1c0df6d3f70d5f1d7cd"

        def install
          bin.install "runny"
          bash_completion.install "completions/runny.bash" => "runny"
          fish_completion.install "completions/runny.fish"
          zsh_completion.install "completions/runny.zsh" => "_runny"
        end
      end
    end
  end
end
