# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runny < Formula
  desc ""
  homepage "https://github.com/simonwhitaker/runny"
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/runny/releases/download/v0.0.6/runny_Darwin_x86_64.tar.gz"
      sha256 "38c62396db8ba5afa04909e4b7f9bcc25c38309ab6b97052448fb28eed4f4240"

      def install
        bin.install "runny"
        bash_completion.install "completions/runny.bash" => "runny"
        fish_completion.install "completions/runny.fish"
        zsh_completion.install "completions/runny.zsh" => "_runny"
      end
    end
    on_arm do
      url "https://github.com/simonwhitaker/runny/releases/download/v0.0.6/runny_Darwin_arm64.tar.gz"
      sha256 "85ce7f422f8b30e4b090f2bd7b875a0ac5b1fa1a4bdcb4279163153f5e56bcef"

      def install
        bin.install "runny"
        bash_completion.install "completions/runny.bash" => "runny"
        fish_completion.install "completions/runny.fish"
        zsh_completion.install "completions/runny.zsh" => "_runny"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonwhitaker/runny/releases/download/v0.0.6/runny_Linux_x86_64.tar.gz"
        sha256 "181f8978b82ba67235c51467f4b84a7fc28837d86a9d17f7a8685f77df057091"

        def install
          bin.install "runny"
          bash_completion.install "completions/runny.bash" => "runny"
          fish_completion.install "completions/runny.fish"
          zsh_completion.install "completions/runny.zsh" => "_runny"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonwhitaker/runny/releases/download/v0.0.6/runny_Linux_arm64.tar.gz"
        sha256 "a6a37a13dc9151c06100be8d83f18b47123f1456c4e2784e5c2639aec547b9cf"

        def install
          bin.install "runny"
          bash_completion.install "completions/runny.bash" => "runny"
          fish_completion.install "completions/runny.fish"
          zsh_completion.install "completions/runny.zsh" => "_runny"
        end
      end
    end
  end
end
