# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellsnake < Formula
  desc ""
  homepage "https://github.com/simonwhitaker/shellsnake"
  version "1.0.3"

  disable! date: "2025-12-14", because: "the cask should be used now instead", replacement_cask: "shellsnake"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/shellsnake/releases/download/v1.0.2/shellsnake_Darwin_x86_64.tar.gz"
      sha256 "48947aa554b941dc59deb30a2df686b2695825cbe52cc5097e533b263aee3bcd"

      def install
        bin.install "shellsnake"
      end
    end
    on_arm do
      url "https://github.com/simonwhitaker/shellsnake/releases/download/v1.0.2/shellsnake_Darwin_arm64.tar.gz"
      sha256 "cd90bfd46ee0ea331031846eea4358f74ae30684efffc1dc16f9169508e0ac94"

      def install
        bin.install "shellsnake"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonwhitaker/shellsnake/releases/download/v1.0.2/shellsnake_Linux_x86_64.tar.gz"
        sha256 "b1269737edc2e453be0f15533c827a8b6d9093fa4766cca2f7d9eb446ebd9cca"

        def install
          bin.install "shellsnake"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonwhitaker/shellsnake/releases/download/v1.0.2/shellsnake_Linux_arm64.tar.gz"
        sha256 "811ef38547b8f8435b0e750a91da83d1d9f9beb1e52fcd03e0239b818a62a780"

        def install
          bin.install "shellsnake"
        end
      end
    end
  end
end
