# This file was generated by GoReleaser. DO NOT EDIT.
cask "babbl" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "d05773f8501038cd4ea7f58ce87a18f4b001c32df5e9beba704fe9fc9971f282"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d7973f019aabbd1fcb12aea76e905ddd4a48be7ed6626a3e97ccc2423313d0fc"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "588e0888b4055cd0317388af8e71fe97175872f8887556f52d94da4d207703f2"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a12350ebab00e791e1adde8791bf0d5c362aa702c36aeb33d6fbaf6176f1900b"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Linux_arm64.tar.gz"
    end
  end

  name "babbl"
  desc ""
  homepage "https://github.com/simonwhitaker/babbl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "babbl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/babbl"]
    end
  end
  generate_completions_from_executable "babbl", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
