# This file was generated by GoReleaser. DO NOT EDIT.
cask "babbl" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "450d849adb8832a3a53a970e10cf84e3e386a90e99de599153f57549c3d8738e"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0e0f42edcde60944afe71d064c2880b22c2bcd9356d42cb54952e5e76253519d"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5d2385aa4e6d6c710368d220074c9fdbf733e974c2b77949d69c7d8a74d1a25d"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f145120d63bc2fc587517d1467e644577366637fc918c373447001c425968122"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Linux_arm64.tar.gz"
    end
  end

  name "babbl"
  desc ""
  homepage "https://github.com/simonwhitaker/babbl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "babbl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/babbl"]
    end
  end
  generate_completions_from_executable "babbl",
    shell_parameter_format: :cobra

  # No zap stanza required

end
