# This file was generated by GoReleaser. DO NOT EDIT.
cask "babbl" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "acd0015fd3d79a9c4ab88cc6bd9267f36fd1201575d2903d1043e9d0a32ef2b2"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3bb700366e867d42e1a165fa383365c37e1d95f2fce756c95b2f066c2ce7ddd3"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b97d4e35dd34552401890b87256b92f4f068b668c5e14c170bc7c8a3cb2e20a"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b967484a34942185066b3b504008890c0b22e8e03ff407c1495097c5335a348a"
      url "https://github.com/simonwhitaker/babbl/releases/download/v#{version}/babbl_Linux_arm64.tar.gz"
    end
  end

  name "babbl"
  desc ""
  homepage "https://github.com/simonwhitaker/babbl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "babbl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/babbl"]
    end
  end
  generate_completions_from_executable "babbl",
    shell_parameter_format: :cobra

  # No zap stanza required

end
