# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-history" do
  name "claude-history"
  desc ""
  homepage "https://github.com/simonwhitaker/claude-code-history"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-history"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_darwin_amd64.tar.gz"
      sha256 "51610fb4267d8c8f53f3028858dd2d5845f968618c49b7e1b513b194d8b68eb7"
    end
    on_arm do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_darwin_arm64.tar.gz"
      sha256 "f54d193ad0182a0632e48de50346d83afc5555b0f75a8fc392d1a7423fc057cf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_linux_amd64.tar.gz"
      sha256 "36275471b9e306310b1e7e5697e4921befd68a2471cdcc40f2fc5caa6ab6d148"
    end
    on_arm do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_linux_arm64.tar.gz"
      sha256 "5b9e03efaf289199342894ba15d528e25fae230c7ce1ae5632a1e5bd3ad4f144"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-history"]
    end
  end

  # No zap stanza required
end
