# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-history" do
  name "claude-history"
  desc ""
  homepage "https://github.com/simonwhitaker/claude-code-history"
  version "0.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-history"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_darwin_amd64.tar.gz"
      sha256 "e2ad2d8310290e94eb575e0561fa22c4c3ae57d272e075d7df7499b4554203bc"
    end
    on_arm do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_darwin_arm64.tar.gz"
      sha256 "d0778740ab64d5737e6e5365073a6c1a145fe36e687fbdb5a5db7c9609d0a0fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_linux_amd64.tar.gz"
      sha256 "820cfc25ffd45e4de00598ffb5182ce95d5f31157ab41d51d89eb8c709869290"
    end
    on_arm do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_linux_arm64.tar.gz"
      sha256 "df311059af6d22eb327e0a663d418a022a2b2a1b8bbf291382ecd72529b3c7a6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-history"]
    end
  end

  # No zap stanza required
end
