# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-history" do
  name "claude-history"
  desc ""
  homepage "https://github.com/simonwhitaker/claude-code-history"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-history"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_darwin_amd64.tar.gz"
      sha256 "98b24f276fa3dd92d16f72f0374152c7d91cffe8acc7312445101456a040d134"
    end
    on_arm do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_darwin_arm64.tar.gz"
      sha256 "53d4b091ab58a9652a45db662f14f2b62953589a431d8af9508fa55bd92b43a2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_linux_amd64.tar.gz"
      sha256 "c6689933d15535908547f411cf474a879ea7ba2a8081d7c0f064c9629328df6a"
    end
    on_arm do
      url "https://github.com/simonwhitaker/claude-code-history/releases/download/v#{version}/claude-history_#{version}_linux_arm64.tar.gz"
      sha256 "0d6ec1053ffe43f50ced3bd264b57eac91c9bedb7858860d604baca5420975f0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-history"]
    end
  end

  # No zap stanza required
end
