# This file was generated by GoReleaser. DO NOT EDIT.
cask "gibo" do
  version "3.0.18"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Darwin_x86_64.tar.gz"
      sha256 "c482b79f4c25bcf697cd64961dd61752b13fe9a1312365e660bacb272b3796bd"
    end
    on_arm do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Darwin_arm64.tar.gz"
      sha256 "76aa625e6a8af6021c53ea1d03d8092fca421324cd2ab34cbdd7fea7fea09b62"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Linux_x86_64.tar.gz"
      sha256 "198421a3e00662a77c7e7bf5f698bdec564e43f24e14dc7764c7f7b8d6350ca5"
    end
    on_arm do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Linux_arm64.tar.gz"
      sha256 "524115b87141344de1dde880e976fab061d233ac771b8e167a15466e11cd026e"
    end
  end

  name "gibo"
  desc ""
  homepage "https://github.com/simonwhitaker/gibo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gibo"
  generate_completions_from_executable "gibo", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :powershell]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gibo"]
    end
  end

  # No zap stanza required

end
