# This file was generated by GoReleaser. DO NOT EDIT.
cask "gibo" do
  version "3.0.21"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Darwin_x86_64.tar.gz"
      sha256 "1a967eae281add27d6e53a839127dc52870c51b48bf0f5fd929e3f65722ad9cf"
    end
    on_arm do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Darwin_arm64.tar.gz"
      sha256 "77bba79cf10b9cb6bd8d2e1f689ea0c25e26958760964cc4ca4825f0c6137afe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Linux_x86_64.tar.gz"
      sha256 "8128bc4fbb253cb62bc8c1519964dced459a82466668708c528efda987d383cd"
    end
    on_arm do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Linux_arm64.tar.gz"
      sha256 "d5b23899f963fc6d951d59be63fa5b9bb3db57dfd676c3741ba1fddcdd1c7677"
    end
  end

  name "gibo"
  desc ""
  homepage "https://github.com/simonwhitaker/gibo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gibo"
  generate_completions_from_executable "gibo",
    shell_parameter_format: :cobra

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gibo"]
    end
  end

  # No zap stanza required

end
