# This file was generated by GoReleaser. DO NOT EDIT.
cask "gibo" do
  name "gibo"
  desc ""
  homepage "https://github.com/simonwhitaker/gibo"
  version "3.0.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gibo"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Darwin_x86_64.tar.gz"
      sha256 "3f11fc2647afdbfcd1c2fef66259d7c3a45c536ad0e9238de8160659a4d84e85"
    end
    on_arm do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Darwin_arm64.tar.gz"
      sha256 "00cb7c74b487628bea5ec3a18e161946290a1cb7a9918517d24f9202d75f0a55"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Linux_x86_64.tar.gz"
      sha256 "f98b704bbed0e2db9e5a67a8ec208dc3e6929c44df1d04b7c938e2c134dc487e"
    end
    on_arm do
      url "https://github.com/simonwhitaker/gibo/releases/download/v#{version}/gibo_Linux_arm64.tar.gz"
      sha256 "65ef4bff9fd67c758bc886eddea44a076fdce54cf4acfbb4cb8bfd85a6253c49"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gibo"]
    end
  end

  # No zap stanza required
end
