# This file was generated by GoReleaser. DO NOT EDIT.
cask "runny" do
  name "runny"
  desc ""
  homepage "https://github.com/simonwhitaker/runny"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runny"
  bash_completion "completions/runny.bash"
  zsh_completion "completions/runny.zsh"
  fish_completion "completions/runny.fish"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Darwin_x86_64.tar.gz"
      sha256 "d04449bb5ac265449c3399da65077a1385e97086e2adafbedf3d6501a40125ef"
    end
    on_arm do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Darwin_arm64.tar.gz"
      sha256 "90a50d6311d1f23401835cd3dd60b7a6bc8f668964f9be252bd3b9e499f13c32"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Linux_x86_64.tar.gz"
      sha256 "05dfb01f9ab743a8485d4784e5a2f3aae6ea1e6b3ef9cc3a9a011e5899b84685"
    end
    on_arm do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Linux_arm64.tar.gz"
      sha256 "85940703395967fba287eb3df5c4e26c73f9ab34c090d798dcbc5e2ec03f9da5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/runny"]
    end
  end

  # No zap stanza required
end
