# This file was generated by GoReleaser. DO NOT EDIT.
cask "runny" do
  name "runny"
  desc ""
  homepage "https://github.com/simonwhitaker/runny"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runny"
  bash_completion "completions/runny.bash"
  zsh_completion "completions/runny.zsh"
  fish_completion "completions/runny.fish"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Darwin_x86_64.tar.gz"
      sha256 "7c8a61efe32d5160bfb660e0eb53b50dca5f499c1b9986b82c3c65aeba563b9a"
    end
    on_arm do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Darwin_arm64.tar.gz"
      sha256 "82a4676cace85de67b8b7c7addb7f89205406ab32b4ef6f555a2d52de0ae1a82"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Linux_x86_64.tar.gz"
      sha256 "229edc25220e9abe4fbfbe52d5e9e6f50c80f9c29d219d6111781904fca651d3"
    end
    on_arm do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Linux_arm64.tar.gz"
      sha256 "72c2a41d35243119ee6b3d366fc8caee4e31383ec1d4847b679531d0d6741ddc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/runny"]
    end
  end

  # No zap stanza required
end
