# This file was generated by GoReleaser. DO NOT EDIT.
cask "runny" do
  name "runny"
  desc ""
  homepage "https://github.com/simonwhitaker/runny"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runny"
  bash_completion "completions/runny.bash"
  zsh_completion "completions/runny.zsh"
  fish_completion "completions/runny.fish"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Darwin_x86_64.tar.gz"
      sha256 "50e2ccf0b1b5e79df69a723534fbcea0eb2e586c10e25b6846da1e5f4f7ce506"
    end
    on_arm do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Darwin_arm64.tar.gz"
      sha256 "6d4ce4f22c79e44791ced9ee5deeebe117c7875c5c251988b33a9e8433948866"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Linux_x86_64.tar.gz"
      sha256 "89ac9f4b590d6a3ef5e4ed5d1271983fa6a720e976218c56a3434c2eb370cd4e"
    end
    on_arm do
      url "https://github.com/simonwhitaker/runny/releases/download/v#{version}/runny_Linux_arm64.tar.gz"
      sha256 "10831414623615c5c013f069dbb12ecc8eec29bbaec127b655b7b6c6a81166ea"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/runny"]
    end
  end

  # No zap stanza required
end
