# This file was generated by GoReleaser. DO NOT EDIT.
cask "shellsnake" do
  name "shellsnake"
  desc ""
  homepage "https://github.com/simonwhitaker/shellsnake"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shellsnake"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/shellsnake/releases/download/v#{version}/shellsnake_Darwin_x86_64.tar.gz"
      sha256 "355a3f2615e0b6d190625228cf766643b4a4fc495ead2e6bb9e546d47597541c"
    end
    on_arm do
      url "https://github.com/simonwhitaker/shellsnake/releases/download/v#{version}/shellsnake_Darwin_arm64.tar.gz"
      sha256 "d7c81dc426257d72ef3783f3471dab5135b28269dcaed0a8d05547d1c46f7cf6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/simonwhitaker/shellsnake/releases/download/v#{version}/shellsnake_Linux_x86_64.tar.gz"
      sha256 "3d80715380526bab962050cd2748562fefa3ecb8d88376c3e3108eb11c64759f"
    end
    on_arm do
      url "https://github.com/simonwhitaker/shellsnake/releases/download/v#{version}/shellsnake_Linux_arm64.tar.gz"
      sha256 "6265b1a7f2f446e874cd27a06eda81c53024ce8c0fbdd0d2c7ddbc5454acfa71"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shellsnake"]
    end
  end

  # No zap stanza required
end
