# This file was generated by GoReleaser. DO NOT EDIT.
cask "shellsnake" do
  name "shellsnake"
  desc ""
  homepage "https://github.com/simonwhitaker/shellsnake"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shellsnake"

  on_macos do
    on_intel do
      url "https://github.com/simonwhitaker/shellsnake/releases/download/v#{version}/shellsnake_Darwin_x86_64.tar.gz"
      sha256 "b04378a84a705f790094f130956053b7e9888b7676152b153cec18ca1dccef14"
    end
    on_arm do
      url "https://github.com/simonwhitaker/shellsnake/releases/download/v#{version}/shellsnake_Darwin_arm64.tar.gz"
      sha256 "bd5ca0de1710ed42663e5428f20f44e0ed48eceafda598068cdf32fb689fc1bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/simonwhitaker/shellsnake/releases/download/v#{version}/shellsnake_Linux_x86_64.tar.gz"
      sha256 "5ff859689a7993b88bedd9e49b0d899d82063446c9cd09a849e34436b77ab0e5"
    end
    on_arm do
      url "https://github.com/simonwhitaker/shellsnake/releases/download/v#{version}/shellsnake_Linux_arm64.tar.gz"
      sha256 "7827f9eae9ddb166c0c84c0cd5445f3b4806b0f4e6261348dd4ae423901067b3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shellsnake"]
    end
  end

  # No zap stanza required
end
